services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kanishk
      POSTGRES_PASSWORD: kanishk
      POSTGRES_DB: asynctasks
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  vault:
    image: hashicorp/vault:1.15
    container_name: autodeploy-vault-1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}}'
    ports:
      - "8200:8200"
    volumes:
      - ./vault_data:/vault/file # Maps local folder 'vault_data' to Vault storage
    cap_add:
      - IPC_LOCK

  traefik:
    image: traefik:v2.11
    user: root
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - autodeploy-net

networks:
  autodeploy-net:
    name: autodeploy-net

volumes:
  postgres_data:
  redis_data: