services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kanishk
      POSTGRES_PASSWORD: kanishk
      POSTGRES_DB: asynctasks
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"